# Generated by Django 4.1.1 on 2023-03-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(blank=True, max_length=30, null=True)),
                ('player2', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
